spring:
  application:
    name: User auth service # Info
  main:
    banner-mode: off # Conf.
  datasource:
    url: jdbc:postgresql://localhost:5432/lobby # Conf.
    username: be # Conf.
    password: secret # Conf.
  jpa:
    open-in-view: false
  web:
    resources:
      add-mappings: false


# Toggle this to log all requests and responses
#logging.level.org.zalando.logbook: TRACE
#logbook.secure-filter.enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8080 # Info
  servlet:
    context-path: /api/auth # Conf.

springdoc:
  api-docs:
    enabled: true # Conf.
    path: /public/v3/api-docs
  swagger-ui:
    oauth:
      client-id: external-client # Conf. Helps with the OAuth2 login
    path: /public/docs # Conf. The path to the Swagger UI
    url: /public/v3/api-docs # Conf. The URL to the Swagger API docs

svc:
  keycloak:
    auth-server-url: https://rso-keycloak.janvasiljevic.com
    client-id: external-client
    realm: aga.rso
  # For dev.: Create 'application-local.yaml' in 'src/main/resources' with sensitive data
  keycloak-admin:
    server-url: https://rso-keycloak.janvasiljevic.com
    client-id:
    realm:
    username:
    password:
    frontend-client-id: frontend-client
    frontend-realm: "aga.rso"
  auth-forward:
    log-x-forwarded-headers: true