spring:
  application:
    name: User auth service # Info
  main:
    banner-mode: off # Conf.
  datasource:
    url: jdbc:postgresql://localhost:5432/lobby # Conf.
    username: be # Conf.
    password: secret # Conf.
  jpa:
    open-in-view: false
  web:
    resources:
      add-mappings: false
  servlet:
    context-path: /api/lobby # Conf.


server:
  port: 8080 # Info

springdoc:
  api-docs:
    enabled: true # Conf.
    path: /public/v3/api-docs
  swagger-ui:
    oauth:
      client-id: external-client # Conf. Helps with the OAuth2 login
    path: /public/docs # Conf. The path to the Swagger UI
    url: /public/v3/api-docs # Conf. The URL to the Swagger API docs

svc:
  keycloak:
    auth-server-url: https://rso-keycloak.janvasiljevic.com
    client-id: external-client
    realm: test
  auth-forward:
    log-x-forwarded-headers: true

